---
title: "Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval = FALSE}
library(dmpredict)
library(dplyr)
data <- readRDS('/inst/extdata/testdata.RDS') %>%
  filter(dropped == 'Keep') %>%
  rename(study_id = id_study,
         fpg_clean = fgl_f,
         hba1c_clean = hba1c_f)

## Required columns are:
# iso: ISO-alpha-3 code for a country
# age: age in years
# sex: sex coded as 'female' and 'male'
# study_id: unique ID for each study or each round of a series of studies
# medication: whether using medication for diabetes: yes = 1, no = 0, missing = NA
## Plus at least one of the following:
# fpg_clean: cleaned FPG (mmol/L)
# hba1c_clean: cleaned HbA1c (%)
## Optional covariates for prediction:
# bmi_clean: cleaned body-mass index (kg/m2)
# handheld_fpg: whether FPG was measured using POC handheld device = 1, lab based measurement = 0, unknown = NA
# handheld_a1c: whether HbA1c was measured using POC handheld device = 1, lab based measurement = 0, unknown = NA

## If iso is not recognized
# provide a string with one of the following and name as 'Superregion'
# 'High-income western', 'Central and Eastern Europe', 'Latin America and Caribbean',
# 'Southeast Asia, East Asia and the Pacific', 'Central Asia, Middle East and North Africa',
# 'South Asia', 'Sub-Saharan Africa', 'Oceania'

## Transform columns to use in the prediction equations

df <- transform_data(data)

## Make predictions
# predict_missing_fpg or hba1c functions return a probability that the predicted biomarker
# is over the diagnostic threshold for diabetes, i.e. FPG >=7.0 mmol/L and HbA1c >=6.5%

data$predicted_a1c <- predict_missing_hba1c(df, cw_model_coefs, return_draws = FALSE, verbose = FALSE)
data$predicted_fpg <- predict_missing_fpg(df, cw_model_coefs, return_draws = FALSE, verbose = FALSE)

# using 'return_draws = TRUE' will return the N draws (default = 2000) of predictions in a matrix

res1 <- predict_missing_hba1c(df, cw_model_coefs, return_draws = TRUE, verbose = FALSE)
res2 <- predict_missing_fpg(df, cw_model_coefs, return_draws = TRUE, verbose = FALSE)

data$predicted_a1c2 <- res1$predicted_a1c
data$predicted_fpg2 <- res2$predicted_fpg
print(dim(res1$mat_predicted_a1c))
print(dim(res2$mat_predicted_fpg))

identical(data$predicted_a1c, data$predicted_a1c2)
identical(data$predicted_fpg, data$predicted_fpg2)
```
